version: 2.1
commands:
  build-image:
    description: 'Builds and pushes a docker image'
    parameters:
      env:
        type: string
        default: 'dev'
    steps:
      - setup_remote_docker
#          docker_layer_caching: true

      - checkout

      - run:
          name: Create docker image and push to Docker Hub
          command: |
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            VERSION=$(node -p -e "require('./package.json').version")
            docker build -f docker/<< parameters.env >>/Dockerfile -t ianjamieson/deploying-angular-to-digitalocean-with-circleci:<< parameters.env >>-${VERSION}-${CIRCLE_BUILD_NUM} .
            docker push ianjamieson/deploying-angular-to-digitalocean-with-circleci:<< parameters.env >>-${VERSION}-${CIRCLE_BUILD_NUM}

jobs:

  build-dev-image:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/angular

    steps:
      - build-image:
          env: dev

  build-staging-image:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/angular

    steps:
      - build-image:
          env: staging

  build-production-image:
    docker:
      - image: circleci/node:12.13.0

    working_directory: ~/angular

    steps:
      - build-image:
          env: production

workflows:
  version: 2
  main:
    jobs:
    - build-dev-image:
        filters:
          branches:
            only:
            - develop

    - build-staging-image:
        filters:
          branches:
            only:
            - /release-.*/

    - build-production-image:
        filters:
          branches:
            only:
            - /master/
